#include <stdbool.h>
#include <stddef.h>

#include <valgrind/cachegrind.h>
#include <valgrind/callgrind.h>
#include <valgrind/dhat.h>
#include <valgrind/drd.h>
#include <valgrind/helgrind.h>
#include <valgrind/memcheck.h>
#include <valgrind/valgrind.h>

const unsigned int VALGRIND_MAJOR = __VALGRIND_MAJOR__;
const unsigned int VALGRIND_MINOR = __VALGRIND_MINOR__;

int vg_print(char *msg) { 
  return VALGRIND_PRINTF("%s", msg); 
}

int vg_print_backtrace(char *msg) {
  return VALGRIND_PRINTF_BACKTRACE("%s", msg);
}

size_t vg_do_client_request(size_t _zzq_default, size_t _zzq_request,
                            size_t _zzq_arg1, size_t _zzq_arg2,
                            size_t _zzq_arg3, size_t _zzq_arg4,
                            size_t _zzq_arg5) {
  return VALGRIND_DO_CLIENT_REQUEST_EXPR(_zzq_default, _zzq_request, _zzq_arg1,
                                         _zzq_arg2, _zzq_arg3, _zzq_arg4,
                                         _zzq_arg5);
}


typedef enum {
#ifdef VG_USERREQ__RUNNING_ON_VALGRIND
  CG_USERREQ__RUNNING_ON_VALGRIND = VG_USERREQ__RUNNING_ON_VALGRIND,
#else
  CG_USERREQ__RUNNING_ON_VALGRIND = 0,
#endif
#ifdef VG_USERREQ__DISCARD_TRANSLATIONS
  CG_USERREQ__DISCARD_TRANSLATIONS = VG_USERREQ__DISCARD_TRANSLATIONS,
#else
  CG_USERREQ__DISCARD_TRANSLATIONS = 1,
#endif
#ifdef VG_USERREQ__CLIENT_CALL0
  CG_USERREQ__CLIENT_CALL0 = VG_USERREQ__CLIENT_CALL0,
#else
  CG_USERREQ__CLIENT_CALL0 = 2,
#endif
#ifdef VG_USERREQ__CLIENT_CALL1
  CG_USERREQ__CLIENT_CALL1 = VG_USERREQ__CLIENT_CALL1,
#else
  CG_USERREQ__CLIENT_CALL1 = 3,
#endif
#ifdef VG_USERREQ__CLIENT_CALL2
  CG_USERREQ__CLIENT_CALL2 = VG_USERREQ__CLIENT_CALL2,
#else
  CG_USERREQ__CLIENT_CALL2 = 4,
#endif
#ifdef VG_USERREQ__CLIENT_CALL3
  CG_USERREQ__CLIENT_CALL3 = VG_USERREQ__CLIENT_CALL3,
#else
  CG_USERREQ__CLIENT_CALL3 = 5,
#endif
#ifdef VG_USERREQ__COUNT_ERRORS
  CG_USERREQ__COUNT_ERRORS = VG_USERREQ__COUNT_ERRORS,
#else
  CG_USERREQ__COUNT_ERRORS = 6,
#endif
#ifdef VG_USERREQ__GDB_MONITOR_COMMAND
  CG_USERREQ__GDB_MONITOR_COMMAND = VG_USERREQ__GDB_MONITOR_COMMAND,
#else
  CG_USERREQ__GDB_MONITOR_COMMAND = 7,
#endif
#ifdef VG_USERREQ__CLO_CHANGE
  CG_USERREQ__CLO_CHANGE = VG_USERREQ__CLO_CHANGE,
#else
  CG_USERREQ__CLO_CHANGE = 8,
#endif
#ifdef VG_USERREQ__MALLOCLIKE_BLOCK
  CG_USERREQ__MALLOCLIKE_BLOCK = VG_USERREQ__MALLOCLIKE_BLOCK,
#else
  CG_USERREQ__MALLOCLIKE_BLOCK = 9,
#endif
#ifdef VG_USERREQ__RESIZEINPLACE_BLOCK
  CG_USERREQ__RESIZEINPLACE_BLOCK = VG_USERREQ__RESIZEINPLACE_BLOCK,
#else
  CG_USERREQ__RESIZEINPLACE_BLOCK = 10,
#endif
#ifdef VG_USERREQ__FREELIKE_BLOCK
  CG_USERREQ__FREELIKE_BLOCK = VG_USERREQ__FREELIKE_BLOCK,
#else
  CG_USERREQ__FREELIKE_BLOCK = 11,
#endif
#ifdef VG_USERREQ__CREATE_MEMPOOL
  CG_USERREQ__CREATE_MEMPOOL = VG_USERREQ__CREATE_MEMPOOL,
#else
  CG_USERREQ__CREATE_MEMPOOL = 12,
#endif
#ifdef VG_USERREQ__DESTROY_MEMPOOL
  CG_USERREQ__DESTROY_MEMPOOL = VG_USERREQ__DESTROY_MEMPOOL,
#else
  CG_USERREQ__DESTROY_MEMPOOL = 13,
#endif
#ifdef VG_USERREQ__MEMPOOL_ALLOC
  CG_USERREQ__MEMPOOL_ALLOC = VG_USERREQ__MEMPOOL_ALLOC,
#else
  CG_USERREQ__MEMPOOL_ALLOC = 14,
#endif
#ifdef VG_USERREQ__MEMPOOL_FREE
  CG_USERREQ__MEMPOOL_FREE = VG_USERREQ__MEMPOOL_FREE,
#else
  CG_USERREQ__MEMPOOL_FREE = 15,
#endif
#ifdef VG_USERREQ__MEMPOOL_TRIM
  CG_USERREQ__MEMPOOL_TRIM = VG_USERREQ__MEMPOOL_TRIM,
#else
  CG_USERREQ__MEMPOOL_TRIM = 16,
#endif
#ifdef VG_USERREQ__MOVE_MEMPOOL
  CG_USERREQ__MOVE_MEMPOOL = VG_USERREQ__MOVE_MEMPOOL,
#else
  CG_USERREQ__MOVE_MEMPOOL = 17,
#endif
#ifdef VG_USERREQ__MEMPOOL_CHANGE
  CG_USERREQ__MEMPOOL_CHANGE = VG_USERREQ__MEMPOOL_CHANGE,
#else
  CG_USERREQ__MEMPOOL_CHANGE = 18,
#endif
#ifdef VG_USERREQ__MEMPOOL_EXISTS
  CG_USERREQ__MEMPOOL_EXISTS = VG_USERREQ__MEMPOOL_EXISTS,
#else
  CG_USERREQ__MEMPOOL_EXISTS = 19,
#endif
#ifdef VG_USERREQ__PRINTF
  CG_USERREQ__PRINTF = VG_USERREQ__PRINTF,
#else
  CG_USERREQ__PRINTF = 20,
#endif
#ifdef VG_USERREQ__PRINTF_BACKTRACE
  CG_USERREQ__PRINTF_BACKTRACE = VG_USERREQ__PRINTF_BACKTRACE,
#else
  CG_USERREQ__PRINTF_BACKTRACE = 21,
#endif
#ifdef VG_USERREQ__PRINTF_VALIST_BY_REF
  CG_USERREQ__PRINTF_VALIST_BY_REF = VG_USERREQ__PRINTF_VALIST_BY_REF,
#else
  CG_USERREQ__PRINTF_VALIST_BY_REF = 22,
#endif
#ifdef VG_USERREQ__PRINTF_BACKTRACE_VALIST_BY_REF
  CG_USERREQ__PRINTF_BACKTRACE_VALIST_BY_REF = VG_USERREQ__PRINTF_BACKTRACE_VALIST_BY_REF,
#else
  CG_USERREQ__PRINTF_BACKTRACE_VALIST_BY_REF = 23,
#endif
#ifdef VG_USERREQ__STACK_REGISTER
  CG_USERREQ__STACK_REGISTER = VG_USERREQ__STACK_REGISTER,
#else
  CG_USERREQ__STACK_REGISTER = 24,
#endif
#ifdef VG_USERREQ__STACK_DEREGISTER
  CG_USERREQ__STACK_DEREGISTER = VG_USERREQ__STACK_DEREGISTER,
#else
  CG_USERREQ__STACK_DEREGISTER = 25,
#endif
#ifdef VG_USERREQ__STACK_CHANGE
  CG_USERREQ__STACK_CHANGE = VG_USERREQ__STACK_CHANGE,
#else
  CG_USERREQ__STACK_CHANGE = 26,
#endif
#ifdef VG_USERREQ__LOAD_PDB_DEBUGINFO
  CG_USERREQ__LOAD_PDB_DEBUGINFO = VG_USERREQ__LOAD_PDB_DEBUGINFO,
#else
  CG_USERREQ__LOAD_PDB_DEBUGINFO = 27,
#endif
#ifdef VG_USERREQ__MAP_IP_TO_SRCLOC
  CG_USERREQ__MAP_IP_TO_SRCLOC = VG_USERREQ__MAP_IP_TO_SRCLOC,
#else
  CG_USERREQ__MAP_IP_TO_SRCLOC = 28,
#endif
#ifdef VG_USERREQ__CHANGE_ERR_DISABLEMENT
  CG_USERREQ__CHANGE_ERR_DISABLEMENT = VG_USERREQ__CHANGE_ERR_DISABLEMENT,
#else
  CG_USERREQ__CHANGE_ERR_DISABLEMENT = 29,
#endif
#ifdef VG_USERREQ__VEX_INIT_FOR_IRI
  CG_USERREQ__VEX_INIT_FOR_IRI = VG_USERREQ__VEX_INIT_FOR_IRI,
#else
  CG_USERREQ__VEX_INIT_FOR_IRI = 30,
#endif
#ifdef VG_USERREQ__INNER_THREADS
  CG_USERREQ__INNER_THREADS = VG_USERREQ__INNER_THREADS,
#else
  CG_USERREQ__INNER_THREADS = 31,
#endif
} CG_ValgrindClientRequest;

typedef enum {
#ifdef VG_USERREQ__DUMP_STATS
  CG_USERREQ__DUMP_STATS = VG_USERREQ__DUMP_STATS,
#else
  CG_USERREQ__DUMP_STATS = 0,
#endif
#ifdef VG_USERREQ__ZERO_STATS
  CG_USERREQ__ZERO_STATS = VG_USERREQ__ZERO_STATS,
#else
  CG_USERREQ__ZERO_STATS = 1,
#endif
#ifdef VG_USERREQ__TOGGLE_COLLECT
  CG_USERREQ__TOGGLE_COLLECT = VG_USERREQ__TOGGLE_COLLECT,
#else
  CG_USERREQ__TOGGLE_COLLECT = 2,
#endif
#ifdef VG_USERREQ__DUMP_STATS_AT
  CG_USERREQ__DUMP_STATS_AT = VG_USERREQ__DUMP_STATS_AT,
#else
  CG_USERREQ__DUMP_STATS_AT = 3,
#endif
#ifdef VG_USERREQ__START_INSTRUMENTATION
  CG_USERREQ__START_INSTRUMENTATION = VG_USERREQ__START_INSTRUMENTATION,
#else
  CG_USERREQ__START_INSTRUMENTATION = 4,
#endif
#ifdef VG_USERREQ__STOP_INSTRUMENTATION
  CG_USERREQ__STOP_INSTRUMENTATION = VG_USERREQ__STOP_INSTRUMENTATION,
#else
  CG_USERREQ__STOP_INSTRUMENTATION = 5,
#endif
} CG_CallgrindClientRequest;

typedef enum {
#ifdef VG_USERREQ__DHAT_AD_HOC_EVENT
  CG_USERREQ__DHAT_AD_HOC_EVENT = VG_USERREQ__DHAT_AD_HOC_EVENT,
#else
  CG_USERREQ__DHAT_AD_HOC_EVENT = 0,
#endif
#ifdef VG_USERREQ__DHAT_HISTOGRAM_MEMORY
  CG_USERREQ__DHAT_HISTOGRAM_MEMORY = VG_USERREQ__DHAT_HISTOGRAM_MEMORY,
#else
  CG_USERREQ__DHAT_HISTOGRAM_MEMORY = 1,
#endif
} CG_DHATClientRequest;

typedef enum {
#ifdef VG_USERREQ__MAKE_MEM_NOACCESS
  CG_USERREQ__MAKE_MEM_NOACCESS = VG_USERREQ__MAKE_MEM_NOACCESS,
#else
  CG_USERREQ__MAKE_MEM_NOACCESS = 0,
#endif
#ifdef VG_USERREQ__MAKE_MEM_UNDEFINED
  CG_USERREQ__MAKE_MEM_UNDEFINED = VG_USERREQ__MAKE_MEM_UNDEFINED,
#else
  CG_USERREQ__MAKE_MEM_UNDEFINED = 1,
#endif
#ifdef VG_USERREQ__MAKE_MEM_DEFINED
  CG_USERREQ__MAKE_MEM_DEFINED = VG_USERREQ__MAKE_MEM_DEFINED,
#else
  CG_USERREQ__MAKE_MEM_DEFINED = 2,
#endif
#ifdef VG_USERREQ__DISCARD
  CG_USERREQ__DISCARD = VG_USERREQ__DISCARD,
#else
  CG_USERREQ__DISCARD = 3,
#endif
#ifdef VG_USERREQ__CHECK_MEM_IS_ADDRESSABLE
  CG_USERREQ__CHECK_MEM_IS_ADDRESSABLE = VG_USERREQ__CHECK_MEM_IS_ADDRESSABLE,
#else
  CG_USERREQ__CHECK_MEM_IS_ADDRESSABLE = 4,
#endif
#ifdef VG_USERREQ__CHECK_MEM_IS_DEFINED
  CG_USERREQ__CHECK_MEM_IS_DEFINED = VG_USERREQ__CHECK_MEM_IS_DEFINED,
#else
  CG_USERREQ__CHECK_MEM_IS_DEFINED = 5,
#endif
#ifdef VG_USERREQ__DO_LEAK_CHECK
  CG_USERREQ__DO_LEAK_CHECK = VG_USERREQ__DO_LEAK_CHECK,
#else
  CG_USERREQ__DO_LEAK_CHECK = 6,
#endif
#ifdef VG_USERREQ__COUNT_LEAKS
  CG_USERREQ__COUNT_LEAKS = VG_USERREQ__COUNT_LEAKS,
#else
  CG_USERREQ__COUNT_LEAKS = 7,
#endif
#ifdef VG_USERREQ__GET_VBITS
  CG_USERREQ__GET_VBITS = VG_USERREQ__GET_VBITS,
#else
  CG_USERREQ__GET_VBITS = 8,
#endif
#ifdef VG_USERREQ__SET_VBITS
  CG_USERREQ__SET_VBITS = VG_USERREQ__SET_VBITS,
#else
  CG_USERREQ__SET_VBITS = 9,
#endif
#ifdef VG_USERREQ__CREATE_BLOCK
  CG_USERREQ__CREATE_BLOCK = VG_USERREQ__CREATE_BLOCK,
#else
  CG_USERREQ__CREATE_BLOCK = 10,
#endif
#ifdef VG_USERREQ__MAKE_MEM_DEFINED_IF_ADDRESSABLE
  CG_USERREQ__MAKE_MEM_DEFINED_IF_ADDRESSABLE = VG_USERREQ__MAKE_MEM_DEFINED_IF_ADDRESSABLE,
#else
  CG_USERREQ__MAKE_MEM_DEFINED_IF_ADDRESSABLE = 11,
#endif
#ifdef VG_USERREQ__COUNT_LEAK_BLOCKS
  CG_USERREQ__COUNT_LEAK_BLOCKS = VG_USERREQ__COUNT_LEAK_BLOCKS,
#else
  CG_USERREQ__COUNT_LEAK_BLOCKS = 12,
#endif
#ifdef VG_USERREQ__ENABLE_ADDR_ERROR_REPORTING_IN_RANGE
  CG_USERREQ__ENABLE_ADDR_ERROR_REPORTING_IN_RANGE = VG_USERREQ__ENABLE_ADDR_ERROR_REPORTING_IN_RANGE,
#else
  CG_USERREQ__ENABLE_ADDR_ERROR_REPORTING_IN_RANGE = 13,
#endif
#ifdef VG_USERREQ__DISABLE_ADDR_ERROR_REPORTING_IN_RANGE
  CG_USERREQ__DISABLE_ADDR_ERROR_REPORTING_IN_RANGE = VG_USERREQ__DISABLE_ADDR_ERROR_REPORTING_IN_RANGE,
#else
  CG_USERREQ__DISABLE_ADDR_ERROR_REPORTING_IN_RANGE = 14,
#endif
} CG_MemcheckClientRequest;

typedef enum {
#ifdef VG_USERREQ__HG_CLEAN_MEMORY
  CG_USERREQ__HG_CLEAN_MEMORY = VG_USERREQ__HG_CLEAN_MEMORY,
#else
  CG_USERREQ__HG_CLEAN_MEMORY = 0,
#endif
#ifdef _VG_USERREQ__HG_SET_MY_PTHREAD_T
  CG_USERREQ__HG_SET_MY_PTHREAD_T = _VG_USERREQ__HG_SET_MY_PTHREAD_T,
#else
  CG_USERREQ__HG_SET_MY_PTHREAD_T = 1,
#endif
#ifdef _VG_USERREQ__HG_PTH_API_ERROR
  CG_USERREQ__HG_PTH_API_ERROR = _VG_USERREQ__HG_PTH_API_ERROR,
#else
  CG_USERREQ__HG_PTH_API_ERROR = 2,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_JOIN_POST
  CG_USERREQ__HG_PTHREAD_JOIN_POST = _VG_USERREQ__HG_PTHREAD_JOIN_POST,
#else
  CG_USERREQ__HG_PTHREAD_JOIN_POST = 3,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_INIT_POST
  CG_USERREQ__HG_PTHREAD_MUTEX_INIT_POST = _VG_USERREQ__HG_PTHREAD_MUTEX_INIT_POST,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_INIT_POST = 4,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_DESTROY_PRE
  CG_USERREQ__HG_PTHREAD_MUTEX_DESTROY_PRE = _VG_USERREQ__HG_PTHREAD_MUTEX_DESTROY_PRE,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_DESTROY_PRE = 5,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_PRE
  CG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_PRE = _VG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_PRE,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_PRE = 6,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_POST
  CG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_POST = _VG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_POST,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_UNLOCK_POST = 7,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_PRE
  CG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_PRE = _VG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_PRE,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_PRE = 8,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_POST
  CG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_POST = _VG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_POST,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_ACQUIRE_POST = 9,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_SIGNAL_PRE
  CG_USERREQ__HG_PTHREAD_COND_SIGNAL_PRE = _VG_USERREQ__HG_PTHREAD_COND_SIGNAL_PRE,
#else
  CG_USERREQ__HG_PTHREAD_COND_SIGNAL_PRE = 10,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_BROADCAST_PRE
  CG_USERREQ__HG_PTHREAD_COND_BROADCAST_PRE = _VG_USERREQ__HG_PTHREAD_COND_BROADCAST_PRE,
#else
  CG_USERREQ__HG_PTHREAD_COND_BROADCAST_PRE = 11,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_WAIT_PRE
  CG_USERREQ__HG_PTHREAD_COND_WAIT_PRE = _VG_USERREQ__HG_PTHREAD_COND_WAIT_PRE,
#else
  CG_USERREQ__HG_PTHREAD_COND_WAIT_PRE = 12,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_WAIT_POST
  CG_USERREQ__HG_PTHREAD_COND_WAIT_POST = _VG_USERREQ__HG_PTHREAD_COND_WAIT_POST,
#else
  CG_USERREQ__HG_PTHREAD_COND_WAIT_POST = 13,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_DESTROY_PRE
  CG_USERREQ__HG_PTHREAD_COND_DESTROY_PRE = _VG_USERREQ__HG_PTHREAD_COND_DESTROY_PRE,
#else
  CG_USERREQ__HG_PTHREAD_COND_DESTROY_PRE = 14,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_INIT_POST
  CG_USERREQ__HG_PTHREAD_RWLOCK_INIT_POST = _VG_USERREQ__HG_PTHREAD_RWLOCK_INIT_POST,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_INIT_POST = 15,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_DESTROY_PRE
  CG_USERREQ__HG_PTHREAD_RWLOCK_DESTROY_PRE = _VG_USERREQ__HG_PTHREAD_RWLOCK_DESTROY_PRE,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_DESTROY_PRE = 16,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_PRE
  CG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_PRE = _VG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_PRE,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_PRE = 17,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_ACQUIRED
  CG_USERREQ__HG_PTHREAD_RWLOCK_ACQUIRED = _VG_USERREQ__HG_PTHREAD_RWLOCK_ACQUIRED,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_ACQUIRED = 18,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_RELEASED
  CG_USERREQ__HG_PTHREAD_RWLOCK_RELEASED = _VG_USERREQ__HG_PTHREAD_RWLOCK_RELEASED,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_RELEASED = 19,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_POST
  CG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_POST = _VG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_POST,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_POST = 20,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_INIT_POST
  CG_USERREQ__HG_POSIX_SEM_INIT_POST = _VG_USERREQ__HG_POSIX_SEM_INIT_POST,
#else
  CG_USERREQ__HG_POSIX_SEM_INIT_POST = 21,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_DESTROY_PRE
  CG_USERREQ__HG_POSIX_SEM_DESTROY_PRE = _VG_USERREQ__HG_POSIX_SEM_DESTROY_PRE,
#else
  CG_USERREQ__HG_POSIX_SEM_DESTROY_PRE = 22,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_RELEASED
  CG_USERREQ__HG_POSIX_SEM_RELEASED = _VG_USERREQ__HG_POSIX_SEM_RELEASED,
#else
  CG_USERREQ__HG_POSIX_SEM_RELEASED = 23,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_ACQUIRED
  CG_USERREQ__HG_POSIX_SEM_ACQUIRED = _VG_USERREQ__HG_POSIX_SEM_ACQUIRED,
#else
  CG_USERREQ__HG_POSIX_SEM_ACQUIRED = 24,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_BARRIER_INIT_PRE
  CG_USERREQ__HG_PTHREAD_BARRIER_INIT_PRE = _VG_USERREQ__HG_PTHREAD_BARRIER_INIT_PRE,
#else
  CG_USERREQ__HG_PTHREAD_BARRIER_INIT_PRE = 25,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_BARRIER_WAIT_PRE
  CG_USERREQ__HG_PTHREAD_BARRIER_WAIT_PRE = _VG_USERREQ__HG_PTHREAD_BARRIER_WAIT_PRE,
#else
  CG_USERREQ__HG_PTHREAD_BARRIER_WAIT_PRE = 26,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_BARRIER_DESTROY_PRE
  CG_USERREQ__HG_PTHREAD_BARRIER_DESTROY_PRE = _VG_USERREQ__HG_PTHREAD_BARRIER_DESTROY_PRE,
#else
  CG_USERREQ__HG_PTHREAD_BARRIER_DESTROY_PRE = 27,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_PRE
  CG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_PRE = _VG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_PRE,
#else
  CG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_PRE = 28,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_POST
  CG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_POST = _VG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_POST,
#else
  CG_USERREQ__HG_PTHREAD_SPIN_INIT_OR_UNLOCK_POST = 29,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_SPIN_LOCK_PRE
  CG_USERREQ__HG_PTHREAD_SPIN_LOCK_PRE = _VG_USERREQ__HG_PTHREAD_SPIN_LOCK_PRE,
#else
  CG_USERREQ__HG_PTHREAD_SPIN_LOCK_PRE = 30,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_SPIN_LOCK_POST
  CG_USERREQ__HG_PTHREAD_SPIN_LOCK_POST = _VG_USERREQ__HG_PTHREAD_SPIN_LOCK_POST,
#else
  CG_USERREQ__HG_PTHREAD_SPIN_LOCK_POST = 31,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_SPIN_DESTROY_PRE
  CG_USERREQ__HG_PTHREAD_SPIN_DESTROY_PRE = _VG_USERREQ__HG_PTHREAD_SPIN_DESTROY_PRE,
#else
  CG_USERREQ__HG_PTHREAD_SPIN_DESTROY_PRE = 32,
#endif
#ifdef _VG_USERREQ__HG_CLIENTREQ_UNIMP
  CG_USERREQ__HG_CLIENTREQ_UNIMP = _VG_USERREQ__HG_CLIENTREQ_UNIMP,
#else
  CG_USERREQ__HG_CLIENTREQ_UNIMP = 33,
#endif
#ifdef _VG_USERREQ__HG_USERSO_SEND_PRE
  CG_USERREQ__HG_USERSO_SEND_PRE = _VG_USERREQ__HG_USERSO_SEND_PRE,
#else
  CG_USERREQ__HG_USERSO_SEND_PRE = 34,
#endif
#ifdef _VG_USERREQ__HG_USERSO_RECV_POST
  CG_USERREQ__HG_USERSO_RECV_POST = _VG_USERREQ__HG_USERSO_RECV_POST,
#else
  CG_USERREQ__HG_USERSO_RECV_POST = 35,
#endif
#ifdef _VG_USERREQ__HG_USERSO_FORGET_ALL
  CG_USERREQ__HG_USERSO_FORGET_ALL = _VG_USERREQ__HG_USERSO_FORGET_ALL,
#else
  CG_USERREQ__HG_USERSO_FORGET_ALL = 36,
#endif
#ifdef _VG_USERREQ__HG_ARANGE_MAKE_UNTRACKED
  CG_USERREQ__HG_ARANGE_MAKE_UNTRACKED = _VG_USERREQ__HG_ARANGE_MAKE_UNTRACKED,
#else
  CG_USERREQ__HG_ARANGE_MAKE_UNTRACKED = 37,
#endif
#ifdef _VG_USERREQ__HG_ARANGE_MAKE_TRACKED
  CG_USERREQ__HG_ARANGE_MAKE_TRACKED = _VG_USERREQ__HG_ARANGE_MAKE_TRACKED,
#else
  CG_USERREQ__HG_ARANGE_MAKE_TRACKED = 38,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_BARRIER_RESIZE_PRE
  CG_USERREQ__HG_PTHREAD_BARRIER_RESIZE_PRE = _VG_USERREQ__HG_PTHREAD_BARRIER_RESIZE_PRE,
#else
  CG_USERREQ__HG_PTHREAD_BARRIER_RESIZE_PRE = 39,
#endif
#ifdef _VG_USERREQ__HG_CLEAN_MEMORY_HEAPBLOCK
  CG_USERREQ__HG_CLEAN_MEMORY_HEAPBLOCK = _VG_USERREQ__HG_CLEAN_MEMORY_HEAPBLOCK,
#else
  CG_USERREQ__HG_CLEAN_MEMORY_HEAPBLOCK = 40,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_INIT_POST
  CG_USERREQ__HG_PTHREAD_COND_INIT_POST = _VG_USERREQ__HG_PTHREAD_COND_INIT_POST,
#else
  CG_USERREQ__HG_PTHREAD_COND_INIT_POST = 41,
#endif
#ifdef _VG_USERREQ__HG_GNAT_MASTER_HOOK
  CG_USERREQ__HG_GNAT_MASTER_HOOK = _VG_USERREQ__HG_GNAT_MASTER_HOOK,
#else
  CG_USERREQ__HG_GNAT_MASTER_HOOK = 42,
#endif
#ifdef _VG_USERREQ__HG_GNAT_MASTER_COMPLETED_HOOK
  CG_USERREQ__HG_GNAT_MASTER_COMPLETED_HOOK = _VG_USERREQ__HG_GNAT_MASTER_COMPLETED_HOOK,
#else
  CG_USERREQ__HG_GNAT_MASTER_COMPLETED_HOOK = 43,
#endif
#ifdef _VG_USERREQ__HG_GET_ABITS
  CG_USERREQ__HG_GET_ABITS = _VG_USERREQ__HG_GET_ABITS,
#else
  CG_USERREQ__HG_GET_ABITS = 44,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_CREATE_BEGIN
  CG_USERREQ__HG_PTHREAD_CREATE_BEGIN = _VG_USERREQ__HG_PTHREAD_CREATE_BEGIN,
#else
  CG_USERREQ__HG_PTHREAD_CREATE_BEGIN = 45,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_CREATE_END
  CG_USERREQ__HG_PTHREAD_CREATE_END = _VG_USERREQ__HG_PTHREAD_CREATE_END,
#else
  CG_USERREQ__HG_PTHREAD_CREATE_END = 46,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_LOCK_PRE
  CG_USERREQ__HG_PTHREAD_MUTEX_LOCK_PRE = _VG_USERREQ__HG_PTHREAD_MUTEX_LOCK_PRE,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_LOCK_PRE = 47,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_MUTEX_LOCK_POST
  CG_USERREQ__HG_PTHREAD_MUTEX_LOCK_POST = _VG_USERREQ__HG_PTHREAD_MUTEX_LOCK_POST,
#else
  CG_USERREQ__HG_PTHREAD_MUTEX_LOCK_POST = 48,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_POST
  CG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_POST = _VG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_POST,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_LOCK_POST = 49,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_PRE
  CG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_PRE = _VG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_PRE,
#else
  CG_USERREQ__HG_PTHREAD_RWLOCK_UNLOCK_PRE = 50,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_POST_PRE
  CG_USERREQ__HG_POSIX_SEM_POST_PRE = _VG_USERREQ__HG_POSIX_SEM_POST_PRE,
#else
  CG_USERREQ__HG_POSIX_SEM_POST_PRE = 51,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_POST_POST
  CG_USERREQ__HG_POSIX_SEM_POST_POST = _VG_USERREQ__HG_POSIX_SEM_POST_POST,
#else
  CG_USERREQ__HG_POSIX_SEM_POST_POST = 52,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_WAIT_PRE
  CG_USERREQ__HG_POSIX_SEM_WAIT_PRE = _VG_USERREQ__HG_POSIX_SEM_WAIT_PRE,
#else
  CG_USERREQ__HG_POSIX_SEM_WAIT_PRE = 53,
#endif
#ifdef _VG_USERREQ__HG_POSIX_SEM_WAIT_POST
  CG_USERREQ__HG_POSIX_SEM_WAIT_POST = _VG_USERREQ__HG_POSIX_SEM_WAIT_POST,
#else
  CG_USERREQ__HG_POSIX_SEM_WAIT_POST = 54,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_SIGNAL_POST
  CG_USERREQ__HG_PTHREAD_COND_SIGNAL_POST = _VG_USERREQ__HG_PTHREAD_COND_SIGNAL_POST,
#else
  CG_USERREQ__HG_PTHREAD_COND_SIGNAL_POST = 55,
#endif
#ifdef _VG_USERREQ__HG_PTHREAD_COND_BROADCAST_POST
  CG_USERREQ__HG_PTHREAD_COND_BROADCAST_POST = _VG_USERREQ__HG_PTHREAD_COND_BROADCAST_POST,
#else
  CG_USERREQ__HG_PTHREAD_COND_BROADCAST_POST = 56,
#endif
#ifdef _VG_USERREQ__HG_RTLD_BIND_GUARD
  CG_USERREQ__HG_RTLD_BIND_GUARD = _VG_USERREQ__HG_RTLD_BIND_GUARD,
#else
  CG_USERREQ__HG_RTLD_BIND_GUARD = 57,
#endif
#ifdef _VG_USERREQ__HG_RTLD_BIND_CLEAR
  CG_USERREQ__HG_RTLD_BIND_CLEAR = _VG_USERREQ__HG_RTLD_BIND_CLEAR,
#else
  CG_USERREQ__HG_RTLD_BIND_CLEAR = 58,
#endif
#ifdef _VG_USERREQ__HG_GNAT_DEPENDENT_MASTER_JOIN
  CG_USERREQ__HG_GNAT_DEPENDENT_MASTER_JOIN = _VG_USERREQ__HG_GNAT_DEPENDENT_MASTER_JOIN,
#else
  CG_USERREQ__HG_GNAT_DEPENDENT_MASTER_JOIN = 59,
#endif
} CG_HelgrindClientRequest;

typedef enum {
#ifdef VG_USERREQ__DRD_GET_VALGRIND_THREAD_ID
  CG_USERREQ__DRD_GET_VALGRIND_THREAD_ID = VG_USERREQ__DRD_GET_VALGRIND_THREAD_ID,
#else
  CG_USERREQ__DRD_GET_VALGRIND_THREAD_ID = 0,
#endif
#ifdef VG_USERREQ__DRD_GET_DRD_THREAD_ID
  CG_USERREQ__DRD_GET_DRD_THREAD_ID = VG_USERREQ__DRD_GET_DRD_THREAD_ID,
#else
  CG_USERREQ__DRD_GET_DRD_THREAD_ID = 1,
#endif
#ifdef VG_USERREQ__DRD_START_SUPPRESSION
  CG_USERREQ__DRD_START_SUPPRESSION = VG_USERREQ__DRD_START_SUPPRESSION,
#else
  CG_USERREQ__DRD_START_SUPPRESSION = 2,
#endif
#ifdef VG_USERREQ__DRD_FINISH_SUPPRESSION
  CG_USERREQ__DRD_FINISH_SUPPRESSION = VG_USERREQ__DRD_FINISH_SUPPRESSION,
#else
  CG_USERREQ__DRD_FINISH_SUPPRESSION = 3,
#endif
#ifdef VG_USERREQ__DRD_START_TRACE_ADDR
  CG_USERREQ__DRD_START_TRACE_ADDR = VG_USERREQ__DRD_START_TRACE_ADDR,
#else
  CG_USERREQ__DRD_START_TRACE_ADDR = 4,
#endif
#ifdef VG_USERREQ__DRD_STOP_TRACE_ADDR
  CG_USERREQ__DRD_STOP_TRACE_ADDR = VG_USERREQ__DRD_STOP_TRACE_ADDR,
#else
  CG_USERREQ__DRD_STOP_TRACE_ADDR = 5,
#endif
#ifdef VG_USERREQ__DRD_ANNOTATE_SEM_INIT_PRE
  CG_USERREQ__DRD_ANNOTATE_SEM_INIT_PRE = VG_USERREQ__DRD_ANNOTATE_SEM_INIT_PRE,
#else
  CG_USERREQ__DRD_ANNOTATE_SEM_INIT_PRE = 6,
#endif
#ifdef VG_USERREQ__DRD_ANNOTATE_SEM_DESTROY_POST
  CG_USERREQ__DRD_ANNOTATE_SEM_DESTROY_POST = VG_USERREQ__DRD_ANNOTATE_SEM_DESTROY_POST,
#else
  CG_USERREQ__DRD_ANNOTATE_SEM_DESTROY_POST = 7,
#endif
#ifdef VG_USERREQ__DRD_ANNOTATE_SEM_WAIT_PRE
  CG_USERREQ__DRD_ANNOTATE_SEM_WAIT_PRE = VG_USERREQ__DRD_ANNOTATE_SEM_WAIT_PRE,
#else
  CG_USERREQ__DRD_ANNOTATE_SEM_WAIT_PRE = 8,
#endif
#ifdef VG_USERREQ__DRD_ANNOTATE_SEM_WAIT_POST
  CG_USERREQ__DRD_ANNOTATE_SEM_WAIT_POST = VG_USERREQ__DRD_ANNOTATE_SEM_WAIT_POST,
#else
  CG_USERREQ__DRD_ANNOTATE_SEM_WAIT_POST = 9,
#endif
#ifdef VG_USERREQ__DRD_ANNOTATE_SEM_POST_PRE
  CG_USERREQ__DRD_ANNOTATE_SEM_POST_PRE = VG_USERREQ__DRD_ANNOTATE_SEM_POST_PRE,
#else
  CG_USERREQ__DRD_ANNOTATE_SEM_POST_PRE = 10,
#endif
#ifdef VG_USERREQ__DRD_RECORD_LOADS
  CG_USERREQ__DRD_RECORD_LOADS = VG_USERREQ__DRD_RECORD_LOADS,
#else
  CG_USERREQ__DRD_RECORD_LOADS = 11,
#endif
#ifdef VG_USERREQ__DRD_RECORD_STORES
  CG_USERREQ__DRD_RECORD_STORES = VG_USERREQ__DRD_RECORD_STORES,
#else
  CG_USERREQ__DRD_RECORD_STORES = 12,
#endif
#ifdef VG_USERREQ__DRD_CLEAN_MEMORY
  CG_USERREQ__DRD_CLEAN_MEMORY = VG_USERREQ__DRD_CLEAN_MEMORY,
#else
  CG_USERREQ__DRD_CLEAN_MEMORY = 13,
#endif
#ifdef VG_USERREQ__DRD_SET_THREAD_NAME
  CG_USERREQ__DRD_SET_THREAD_NAME = VG_USERREQ__DRD_SET_THREAD_NAME,
#else
  CG_USERREQ__DRD_SET_THREAD_NAME = 14,
#endif
} CG_DRDClientRequest;


